"""Markdown report generation from a confirmed finding.

The report includes only *safe* evidence — i.e. data already collected by
passive scanners and stored on the finding. The "Steps to reproduce" section is
constructed from existing evidence only; it never fabricates an exploit chain,
and it explicitly defers to manual review when reproduction cannot be safely
described.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone

from sqlalchemy.orm import Session

from app.config import settings
from app.models import Asset, Evidence, Finding, Program


def _safe_reproduction_steps(finding: Finding, asset: Asset | None) -> str:
    """Construct reproduction steps from safe evidence only."""
    steps: list[str] = []
    target = asset.value if asset else "the affected asset"
    scheme = (asset.scheme + "://") if asset and asset.scheme else ""

    steps.append(f"1. Confirm the asset is in authorized scope: `{scheme}{target}`.")
    if finding.evidence_summary:
        steps.append(
            f"2. Observe the evidence recorded by the scanner: {finding.evidence_summary}."
        )
    else:
        steps.append("2. (No automated evidence captured — manual verification required.)")
    steps.append(
        "3. Manually and safely verify the condition. Do NOT perform destructive "
        "or exploitative actions; any risky validation is flagged for manual review."
    )
    return "\n".join(steps)


def generate_report_markdown(db: Session, finding: Finding) -> tuple[str, str]:
    """Return ``(title, markdown)`` for a finding's report."""
    program: Program | None = db.get(Program, finding.program_id)
    asset: Asset | None = db.get(Asset, finding.asset_id) if finding.asset_id else None
    evidence_items = (
        db.query(Evidence).filter(Evidence.finding_id == finding.id).all()
    )

    title = f"[{finding.severity.upper()}] {finding.title}"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    scope_desc = program.name if program else f"program {finding.program_id}"
    asset_line = "n/a"
    if asset:
        scheme = (asset.scheme + "://") if asset.scheme else ""
        port = f":{asset.port}" if asset.port else ""
        asset_line = f"{scheme}{asset.value}{port}"

    references = []
    if finding.cwe:
        references.append(f"- {finding.cwe}: https://cwe.mitre.org/data/definitions/{_cwe_num(finding.cwe)}.html")
    if finding.owasp:
        references.append(f"- OWASP: {finding.owasp}")
    if finding.scanner_name:
        references.append(f"- Detected by scanner: {finding.scanner_name}")
    references_block = "\n".join(references) if references else "- (none)"

    evidence_block = "\n".join(
        f"- **{e.label}**: {e.description or e.file_path or 'see evidence store'}"
        for e in evidence_items
    ) or (finding.evidence_summary or "- (no evidence attached)")

    review_note = ""
    if finding.manual_review_required:
        review_note = (
            "\n> ⚠️ **Manual review required.** This finding has not been auto-confirmed. "
            "Validate safely before submission.\n"
        )

    markdown = f"""# {title}
{review_note}
## Summary
{finding.description or finding.ai_summary or finding.title}

## Scope
Program: **{scope_desc}** (authorized scope only)

## Affected Asset
{asset_line}

## Severity
**{finding.severity}** (confidence: {finding.confidence})

## Steps to Reproduce
{_safe_reproduction_steps(finding, asset)}

## Evidence
{evidence_block}

## Impact
{finding.impact or "Impact not yet assessed."}

## Remediation
{finding.remediation or "Remediation guidance pending."}

## References
{references_block}

## Timeline
- {now}: Report generated by AutoBugHunter.
- Finding first created: {finding.created_at}
"""
    return title, markdown


def write_report_to_disk(finding_id: int, markdown: str) -> str:
    """Persist the markdown report under the reports directory and return its path."""
    os.makedirs(settings.reports_dir, exist_ok=True)
    path = os.path.join(settings.reports_dir, f"finding_{finding_id}.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(markdown)
    return path


def _cwe_num(cwe: str) -> str:
    digits = "".join(c for c in cwe if c.isdigit())
    return digits or "0"
